{
 "title": "Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Consumer Lag per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup!=\"\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kafka_topic_partitions)", "legendFormat": "Total Partitions" }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition)",
     "legendFormat": "Under Replicated Partitions"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "MessagesIn Per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\",topic!=\"\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  }
 ]
}